### ISSUE TITLE
Lambda scrapers tv show scraper. 

### ISSUE THREAD

**Issue by JFG90** [13Clowns/_scrapers#2]
Would It be possible to take a look at how lambda scrapes shows? For example when I was using IACs version I was able to find Rlsbb links for Narcos Mexico, after switching to your version I only find very few DirectDL links for that show and another that i could find rlsbb links with before. Thanks in advance!

**Comment by 13Clowns** [comment]
rlsbb is fixed, should pull more. 

will be pushed out soon
