### ISSUE TITLE
ScnSrc please and DDLValley 

### ISSUE THREAD

**Issue by lukehansford** [13Clowns/_scrapers#7]
Could you add www.ScnSrc.me and www.ddlvalley.me for debrid scrapers to the new cavitas scrapers.

The first provides tons of links even 4K and many for TV shows. I would say even more than Releasebb that often is down these days.

Best to use the http www.ScnSrc.me link and not Https link because the Https is blocked for many.

Also should RLSBB not be in the Debrid only category?

There also seems to be many non debrid providers not working and could be removed to speed up scraping time.

**Comment by 13Clowns** [comment]
Will be in the next update. 

Trying to only update once a week.
